#!/usr/bin/python

import i3
from subprocess import call

for workspace in i3.get_workspaces():
    if workspace["focused"]:
        call(('notify-send', "Workspace: %s" % workspace["name"]))
        break
